# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        pytest

    - name: Test notebook exploratory analysis
      run: |
        py.test --nbval-lax notebooks/exploratory_analysis_event_data.ipynb

    - name: Test notebook goal kick analysis
      run: |
        py.test --nbval-lax notebooks/goal_kick_analysis.ipynb

    - name: Test notebook passing analysis
      run: |
        py.test --nbval-lax notebooks/passing_analysis.ipynb

    - name: Test notebook expected goal logistic regression
      run: |
        py.test --nbval-lax notebooks/expected_goal_model_lr.ipynb

    - name: Test notebook challenges with gradient boosting
      run: |
        py.test --nbval-lax notebooks/challenges_with_gradient_boosters.ipynb

    - name: Test notebook introduction to tracking data
      run: |
        py.test --nbval-lax notebooks/introduction_to_tracking_data.ipynb